# Generated by Django 4.0.3 on 2022-03-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
