# Generated by Django 4.0.3 on 2022-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_remove_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
